{% set name = "django-survey-and-report" %}
{% set version = "1.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 21c1f9312760d43544ef8454d07b6d222d0245f097078ef7160eb353c802ac00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.5.1
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - django >=2.2,<6
    - django-bootstrap-form >=3.4
    - django-registration >=3.0
    - django-tastypie >=0.14.2
    #- ordereddict >=1.1 requires python 2.6
    - pytz >=2018.9
    - pyyaml >=4.2b1

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(DEBUG=True,ROSETTA_MESSAGES_PER_PAGE=5); django.setup(); import survey"
    #- pip check skipped because ordereddict requires python 2.6
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A django survey app that can export results as CSV or PDF using your native language.
  license: AGPL-3.0-only
  license_file: LICENSE.txt
  home: https://github.com/Pierre-Sassoulas/django-survey

extra:
  recipe-maintainers:
    - rxm7706
